services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_AOF_ENABLED=yes
      - REDIS_PORT_NUMBER=6379
      - REDIS_REPLICATION_MODE=master
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_IO_THREADS=10
      - REDIS_IO_THREADS_DO_READS=true